name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '22'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'any'
          channel: 'stable'

      - name: Get dependencies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build APK
        run: |
          cd flutter_app
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
